### POST /api/users/identity
### DID creation route, meant to be run on onboarding, creates the admin user and generates keypair

POST http://localhost:5000/api/users/identity
Content-Type: application/json

{
  "username" : "user",
  "password": "password",
  "pin": "123456"
}

### POST /api/users/login_with_pin
### Login with pin to a user and get access token

POST http://localhost:5000/api/users/login_with_pin
Content-Type: application/json

{
  "username" : "user",
  "pin": "123456"
}

### POST /api/users/login_with_password
### Login with password to a user and get access token

POST http://localhost:5000/api/users/login_with_password
Content-Type: application/json

{
  "username" : "user",
  "password": "password"
}